spring.application.name=ecommerce-multivendor

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=rockthisparty@123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.port=465
#spring.mail.username=codewithnnt@gmail.com
spring.mail.username=quancong202@gmail.com
spring.mail.password=tuhx zmgg tqug nlyn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true